### ISSUE TITLE
About the module

### ISSUE THREAD

**Issue by rhyhck** [zhjohnchan/ARL#7]
Hi , good job!
When I run the code, I meet the problem:
    "  Traceback (most recent call last):
      File "prepro/prepro_pretraining_data.py", line 12, in <module>
        from OpenKE.train_transe import train_transe
      File "/data/renhongyi/ARL/ARL-master/prepro/OpenKE/train_transe.py", line 8, in <module>
        from OpenKE.openke.data import TrainDataLoader
    ModuleNotFoundError: No module named 'OpenKE.openke.data'  "
Could you tell me how to resolve it?

**Comment by rhyhck** [comment]
I have solved above problem, but I meet a new problem about module:
"OSError: [E050] Can't find model 'en_core_sci_scibert'. It doesn't seem to be a Python package or a valid path to a data directory."
could you help me?
Thanks!
